require "digest/md5"

require_relative "features/support/libs/mongo.rb"

def to_med5(pass)
    return Digest::MD5.hexdigest(pass)
end

task :test do
    puts "Executando uma tarefa de teste"
end

task :local_seeds do

    CONFIG = YAML.load_file(File.join(Dir.pwd, "/features/support/config/local.yml"))

    users = [
        {name: "Matheus ", email: "matheus@qa.com", password: to_med5("pwd123")},
        {name: "Brook", email: "brook@onepiece.com", password: to_med5("teste123")},
        {name: "Frank", email: "frank@onepiece.com", password: to_med5("teste123")},
        {name: "Jção Anúnciate", email: "joao@anunciante.com", password: to_med5("teste123")},
        {name: "Maria Locatária", email: "maria@locataria.com", password: to_med5("teste123")},
    ]

    MongoDB.new.drop_danger
    MongoDB.new.insert_users(users)

    sh "cucumber -p jenkins"
end

task :hmg_seeds do

    CONFIG = YAML.load_file(File.join(Dir.pwd, "/features/support/config/hmg.yml"))

    users = [
        {name: "Matheus ", email: "matheus@qa.com", password: to_med5("pwd123")},
        {name: "Brook", email: "brook@onepiece.com", password: to_med5("teste123")}
    ]

    MongoDB.new.drop_danger
    MongoDB.new.insert_users(users)

    sh "cucumber"
end